### PR TITLE
api_doc nested fix

### PR DESCRIPTION
**Pull request by ifrolikov**
@HugoMario I was found one more mistake... sorry

### CODE REVIEW

**Comment by ifrolikov** [comment]
Model and Api classes generate normally, I have tested :)

**Comment by ifrolikov** [comment]
image

**Comment by HugoMario** [comment]
hey @ifrolikov, sorry for this build issue, we're working on names version refactoring that is causing this mess temporally, i hope :-)

I'll let you know once it's fixed.

**Comment by ifrolikov** [comment]
@HugoMario , Urah! Build is successful! :)

**Comment by HugoMario** [comment]
a lot thanks @ifrolikov !

**Pull request merged**
