### PR TITLE
[typescript-angular] Fix output

### PR DESCRIPTION
**Pull request by cmalard**
Introduced in 4b74540 ( #568 )

Deeply sorry guys... the code is broken in prod for everyone until this is fixed... I will flog myself... @HugoMario

### CODE REVIEW

**Comment by cmalard** [comment]
Dumb question... how can I test it? 🤐

**Comment by HugoMario** [comment]
thanks a lot @cmalard !!

**Comment by HugoMario** [comment]
hmmm, it seems i have been rushing with this. @cmalard , did you figure out how to test? :/

**Comment by cmalard** [comment]
Absolutely not, I'm not against some how-to... ^^

**Pull request merged**
