### PR TITLE
ref swagger-api/swagger-codegen/issues/9210 - update http urls to https

### PR DESCRIPTION
**Pull request by frantuma**
ref swagger-api/swagger-codegen/issues/9210 - update http urls to https

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
This is an incomplete fix.

**Comment by frantuma** [comment]
Thanks for reporting this, could you clarify what is missing? this addresses similar issues as those of  swagger-api/swagger-codegen/issues/9210 fixed in swagger-api/swagger-codegen/pull/9389, but for codegen 3.0.0 branch.

**Comment by JLLeitschuh** [comment]
This does seem to fully resolve the issue:
https://github.com/swagger-api/swagger-codegen/pull/9389

**Comment by frantuma** [comment]
yes, that PR addresses the issues for master branch, while this PR addresses similar fix for the 3.0.0 branch

**Pull request merged**
