### PR TITLE
fix: Use jakarta.servlet import in generated *Api.java when the jakar…

### PR DESCRIPTION
**Pull request by tgillain**
Handle the jakarta parameter in the *Api.java generation

### CODE REVIEW

**Comment by tgillain** [comment]
Fixes #1167

**Comment by HugoMario** [comment]
Thanks a lot @tgillain for this PR

**Comment by Mugibor** [comment]
What other config do we need to use @tgillain ?

<plugin>
                <groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>./api-def/*Api.yaml</inputSpec>
                            <language>spring</language>
                            <output>${project.build.directory}/generated-sources/swagger-codegen</output>
                            <configOptions>
                                <java8>true</java8>
                                <openApiNullable>false</openApiNullable>
                                <modelPackage>x</modelPackage>
                                <apiPackage>Y</apiPackage>
                                <jakarta>true</jakarta>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            This also use the javax.servlet package. Do I need to add another dependency?

**Comment by dgswan** [comment]
@Mugibor you should upgrade at least to `3.0.46` to have the `jakarta` option supported.
```
<plugin>
  <groupId>io.swagger.codegen.v3</groupId>
  <artifactId>swagger-codegen-maven-plugin</artifactId>
  <version>3.0.46</version>
  ...
</plugin>
```

**Comment by Mugibor** [comment]
> @Mugibor you should upgrade at least to `3.0.46` to have the `jakarta` option supported.
> 
> ```
> <plugin>
>   <groupId>io.swagger.codegen.v3</groupId>
>   <artifactId>swagger-codegen-maven-plugin</artifactId>
>   <version>3.0.46</version>
>   ...
> </plugin>
> ```
@dgswan 
Thx, one more question. I'm using currently the 3.0.54 version. While the application running I got an error with the following:
Swagger2SpringBoot class :
java: cannot find symbol
  symbol:   class WebMvcConfigurerAdapter
  location: package org.springframework.web.servlet.config.annotation
  
  Currently I'm migrating from 2.7 to 3.2.3. What should I change to work this java codegen with spring boot v3?

**Comment by tgillain** [comment]
It looks like this is the issue you are facing https://www.baeldung.com/web-mvc-configurer-adapter-deprecated

**Comment by Mugibor** [comment]
`import org.springframework.context.annotation.Configuration;
import org.springframework.format.FormatterRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

@SpringBootApplication
@ComponentScan(basePackages = { "io.swagger", "XX" , "io.swagger.configuration"})
public class Swagger2SpringBoot implements CommandLineRunner {`

I'm not sure of that, this class has the error "cannot find symbol"

**Pull request merged**
