### PR TITLE
Refactor and consolidate Angular Code Generator

### LINKED ISSUE #234: [typescript-angular] Angular 7: An expression of type 'void' cannot be tested for truthiness
formParam.append returns [void](https://github.com/swagger-api/swagger-codegen-generators/blob/789fc8aaaf61daa212797132112cc32419ab1a9f/src/main/resources/mustache/typescript-angular/api.service.mustache#L265)
but below it is flollowed by logical [OR](https://github.com/swagger-api/swagger-codegen-generators/blob/789fc8aaaf61daa212797132112cc32419ab1a9f/src/main/resources/mustache/typescript-angular/api.service.mustache#L295) 
Here is example of generated code:
`let formParams: { append(param: string, value: any): void; };`
```
if (file !== undefined) {
    formParams = formParams.append('file', <any>file) || formParams;
}
```

### PR DESCRIPTION
**Pull request by hypery2k**
* Code Refactorings
* Add several changes (see #120, #236, #277)
* Fixes #234, #347 and #335
* Adding some fixes from [fork](https://github.com/OpenAPITools/openapi-generator)
* Should also solve https://github.com/swagger-api/swagger-codegen/issues/9822

### CODE REVIEW

**Comment by webron** [comment]
Thanks for the submission, @hypery2k. In case you're not familiar with the option - https://github.blog/2019-02-14-introducing-draft-pull-requests.

**Comment by hypery2k** [comment]
oh thanks, didn't notice that possibility on GitHub ;)
Thanks for the hint

**Comment by hypery2k** [comment]
From my tests so far the generation with Angular 6 and 8 is working without issues.

I would like to see this PR merged and will add further functionality in another PR, ok for you @webron ?

**Comment by webron** [comment]
I leave the PR reviews to @HugoMario and @frantuma - they are way more familiar with the code here than me ;)

**Comment by HugoMario** [comment]
LGTM, thanks a lot @hypery2k!!! for this PR

**Review by victorsempere — COMMENTED** [review]
Hello,
Maybe it's missing a change in the api.service.mustache? I'm getting compilation errors and I have fixed it changing the line 279:
let formParams: { append(param: string, value: any): void; };
Into:
let formParams: { append(param: string, value: any): **any;** };

I'm using swagger-codegen-maven-plugin 3.0.27

**Pull request merged**
