### PR TITLE
728 Fix parameter bean validation issues for micronaut code generator

### PR DESCRIPTION
**Pull request by shourien**
- Add bean validations for header parameter for micronaut
- Remove `@NotNull` declared twice in case of query Param
- `@Nullable` Added if required: false or unspecified for a parameter

### CODE REVIEW

**Comment by shourien-vha** [comment]
@HugoMario Do I need to rebase now and resubmit this pull request?

**Comment by shourien** [comment]
@HugoMario Do i need to rebase now and resubmit this pull request?

**Comment by HugoMario** [comment]
thanks a lot @shourien !!

**Comment by HugoMario** [comment]
sorry for delay

**Pull request merged**
