### PR TITLE
Fixed ngPackagr and Angular 8 support

### PR DESCRIPTION
**Pull request by hypery2k**
* Added support for ngPackagr again
* Drop support for Angular version older thant 4.x

see #120

### CODE REVIEW

**Comment by HugoMario** [comment]
thanks a lot @hypery2k for this PR, if you are willing to migrate this changes for [codegen v3](https://github.com/swagger-api/swagger-codegen-generator). Please ,let me know and i can help you with merging

**Comment by HugoMario** [comment]
please, ignore `migrating` stuff comment, just got a bit confuse. Thanks again!

**Comment by hypery2k** [comment]
you're welcome, looking forward to a new release of the maven plugin ;)

**Comment by hypery2k** [comment]
@HugoMario Any plans for a new release aligned with the maven plugin?

**Pull request merged**
