### PR TITLE
#780 python flask dependencies

### PR DESCRIPTION
**Pull request by jstockdi-marstone**
Addresses Issue https://github.com/swagger-api/swagger-codegen-generators/issues/780

Changes include:

 * Incrementing connexion
 * Incrementing flask_test
 * Adding tox to test-requirements.txt

### CODE REVIEW

**Review by ulidtko — APPROVED** [review]
LGTM :heavy_check_mark: 

Please merge.

**Comment by jstockdi-marstone** [comment]
@ulidtko  - Do you have write access to merge?  Maybe @HugoMario  ?  Let me know how I can push this over the line...

**Comment by ulidtko** [comment]
No, I'm not a committer here.

@HugoMario please merge, this fixes https://github.com/zalando/connexion/issues/1149 which is impacting a lot of people. `connexion == 2.2.0` was released almost 2 years ago; as you can see in the issue, updating to `connexion == 2.6.0` in the `swagger-codegen`-generated Python/Flask project did resolve the issue for pretty much everyone there.

The other change proposed in this PR addresses "broken out of the box" unit-testing in the generated skeleton.

Having this change merged (& released) will fix the "getting started with `swagger-codegen`" experience for Python users.

**Comment by HugoMario** [comment]
thanks a lot for this PR!!!

**Pull request merged**
