### PR TITLE
[DefaultCodegenConfig] Handle default parameter values

### PR DESCRIPTION
**Pull request by michaeldavis-wf**
Parameter default values are not being generated. This appears to be due to not copying the values from the Swagger Parameter object over to the Codegen Parameter object. I copied some of [that logic](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2496-L25060) from the master branch and updated it slightly. 

Using this (partial) definition:

```yaml
paths:
  /scim2/Users:
    get:
      summary: Retrieve users
      description: Retrieve a collection of user resources for the authorized organization.
      operationId: listUsers
      parameters:
        - name: startIndex
          description: An integer indicating the 1-based index of the first query result.
          in: query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
```

Generated code used to look like:

```java
@Parameter(in = ParameterIn.QUERY, description = "An integer indicating the 1-based index of the first query result.", schema=@Schema(allowableValues={  }, minimum="1")) @QueryParam("startIndex") Integer startIndex
```

And now looks like:

```java
@Parameter(in = ParameterIn.QUERY, description = "An integer indicating the 1-based index of the first query result.", schema=@Schema(allowableValues={  }, minimum="1")) @DefaultValue("1") @QueryParam("startIndex") Integer startIndex
```

### CODE REVIEW

**Comment by michaeldavis-wf** [comment]
@frantuma, @webron, @HugoMario Could one of you look at this.

**Comment by matthewsullivan-wf** [comment]
@HugoMario thanks for merging our other bugfix. Could I humbly ask you look at this one as well in the next week or so?

**Comment by HugoMario** [comment]
thanks a lot @michaeldavis-wf and @matthewsullivan-wf. 

Please, ping any time you need help with something.

**Comment by matthewsullivan-wf** [comment]
Thank you!

**Comment by michaeldavis-wf** [comment]
Thank you, @HugoMario. 

Are the releases of this repo scheduled, or are they by request?

**Pull request merged**
