### PR TITLE
Resolve header references in responses. Added tests

### PR DESCRIPTION
**Pull request by chris-prop**
Fixes issue #326

### CODE REVIEW

**Comment by HugoMario** [comment]
hi @chris-prop sorry for delay. i want to let you know that `OpenAPI` object has global access for `DefaultCodegenConfig` class. So if you would like to update your PR based on that, it could be great.

**Comment by chris-prop** [comment]
@HugoMario I finally got around to updating this.

**Comment by skrysmanski** [comment]
Isn‘t the propose change a breaking change (because a public method is deleted)?

**Comment by chris-prop** [comment]
> Isn‘t the proposed change a breaking change (because a public method is deleted)?

The only public method I deleted was the one I added in the original PR (that was never merged).

**Comment by skrysmanski** [comment]
You‘re right. My bad.

**Comment by chris-prop** [comment]
Is there something I need to do to get this merged?

**Comment by frantuma** [comment]
thanks!

**Pull request merged**
