### PR TITLE
Php client generator

### PR DESCRIPTION
**Pull request by HugoMario**
PHP client with OAS3 support.

### CODE REVIEW

**Comment by webron** [comment]
:scream:

**Comment by HugoMario** [comment]
Hey @ackintosh @jebentier @ dkarlovi

when you have a chance, would you please check this with `swagger-codegen` branch 3.0.0?

**Comment by HugoMario** [comment]
@dkarlovi

**Comment by HugoMario** [comment]
Hello @mandrean @jfastnacht if you guys have time, can you please help us checking this PR?

**Pull request merged**
